version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: blog_platform_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Simple123
      MYSQL_DATABASE: blog_platform
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d

volumes:
  mysql_data: